# fly.toml app configuration file generated for mise-recipe-recommender on 2026-05-16T23:47:32Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mise-recipe-recommender'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  min_machines_running = 1

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
